# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9919b51e77d2a3a0ec4dca560cd82e06"
name = "non-embeded-app"
handle = "non-embeded-app"
application_url = "https://surrounding-darkness-portugal-closing.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "armughan00.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://surrounding-darkness-portugal-closing.trycloudflare.com/auth/callback",
  "https://surrounding-darkness-portugal-closing.trycloudflare.com/auth/shopify/callback",
  "https://surrounding-darkness-portugal-closing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
