# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85c71fbac30688973d09bb53583012f2"
name = "xml-feed-5"
handle = "xml-feed-5"
application_url = "https://tier-treasure-alive-may.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xml-feed-generator.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://tier-treasure-alive-may.trycloudflare.com/auth/callback",
  "https://tier-treasure-alive-may.trycloudflare.com/auth/shopify/callback",
  "https://tier-treasure-alive-may.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
